#!/bin/sh

cd ~
curl --remote-name https://raw.githubusercontent.com/nickm4062/laptop/update-2018-5-22/mac
curl --remote-name https://raw.githubusercontent.com/nickm4062/laptop/update-2018-5-22/Brewfile
/usr/bin/env bash mac 2>&1 | tee ~/laptop.log
